### ISSUE TITLE
Query parameters being stripped

### ISSUE THREAD

**Issue by ping** [technoboy10/crossorigin.me#70] opened 2016-12-06 03:53 UTC
This can be tested by a codepen from #50 http://codepen.io/anon/pen/JKKaZV

A request to http://api.forismatic.com/api/1.0/?lang=en&method=getQuote&format=json is stripped of its query params and becomes http://api.forismatic.com/api/1.0/ from crossorigin.

**Comment by zd333** [comment] 2016-12-06 20:36
The same with me.

**Comment by eXaminator** [comment] 2016-12-11 21:51
I also seem to have this problem.

**Comment by fega** [comment] 2016-12-24 18:23
the same problem here.

**Comment by tjvr** [comment] 2017-01-09 16:03
Duplicate of #76.

**Closed** 2017-02-18 16:19 UTC
