### ISSUE TITLE
Origin: header is required

### ISSUE THREAD

**Issue by priyachakka26** [technoboy10/crossorigin.me#71] opened 2016-12-07 22:43 UTC
it used to work as normal . 

But today when I am invoking  : https://crossorigin.me/https://www.google.com/ 

I am getting the error : 
Origin: header is required

Any thing changed in there . Can you be able to help me resolving this issue . Thanks a lot for all your help.

**Comment by CosmicWebServices** [comment] 2016-12-07 22:45
Same here

**Comment by tjvr** [comment] 2016-12-08 11:51
This is a deliberate change. Since it's a _CORS_ proxy, this ensures that the proxy can only be used for AJAX requests, and not for casual browsing.

**Comment by priyachakka26** [comment] 2016-12-08 12:53
I am trying to invoke Ajax request from my javascript  and seems the
crossorigin is not responding .so I tried it from browser and both of them
not working .do you suggest me how I can use this proxy again to be
successful.

Thanks again.

**Comment by RafaelKr** [comment] 2016-12-12 16:39
Same here

**Comment by nvisionative** [comment] 2016-12-14 17:35
We are having the same issue via mobile apps using Ionic.

**Comment by liam4** [comment] 2016-12-14 19:37
..It works for me?

```js
fetch('https://crossorigin.me/https://scratch.mit.edu/discuss/m/topic/4464')
  .then(r => r.text())

  // fluff
  .then(t => (new DOMParser()).parseFromString(t, 'text/html'))
  .then(d => Array.from(d.querySelectorAll('.post-content')))
  .then(ps => ps.map(p => p.innerText))
  .then(ps => ps.forEach(p => console.log(p)))
```

Just use `fetch` ([polyfill](http://github.com/github/fetch) if you insist) to make your life easier, it works out of the box w/ crossorigin, zero config.

**Comment by nvisionative** [comment] 2016-12-14 21:14
I am still seeing this:

`XMLHttpRequest cannot load https://crossorigin.me/http://mydomain/api. The 'Access-Control-Allow-Origin' header contains multiple values '*, https://creator.ionic.io', but only one is allowed. Origin 'https://creator.ionic.io' is therefore not allowed access.`

Did something change regarding the header?  It was working fine before and I have confirmed nothing has changed on the Ionic Creator side of things.

**Comment by tjvr** [comment] 2016-12-15 00:21
@nvisionative crossorigin possibly has a bug when accessing an API with an existing ACAO header? Regardless, that is unrelated and you should raise it as a separate issue. :)

**Comment by nvisionative** [comment] 2016-12-15 22:32
Thanks @tjvr - I thought it was related.  I'll create a separate issue.

**Comment by tjvr** [comment] 2016-12-16 11:43
@technoboy10 I suggest not changing this behaviour (we do want to avoid using crossorigin as a proxy for casual browsing!), but rewriting the "Origin header required" page to document the issue more clearly.

Anyone want to send a PR which updates this page to explain what "Origin required" means, and how to fix it? :-)

**Comment by ooade** [comment] 2016-12-21 09:26
@liam4 works fine, if no query exist in the request url.

**Comment by cyphix333** [comment] 2016-12-27 20:38
Same here....... tried it in the browser as well as from codepen, doesn't work.

http://codepen.io/gutterboy/pen/xRXbXy

**Comment by GoToLoop** [comment] 2017-01-09 15:28
URL not working for me either:  
http://CrossOrigin.me/http://api.Zoopla.co.uk/api/v1/property_listings.xml?postcode=ip12&api_key=bmm77zppverakbnfnmtyuky3

Here's the program:
http://p5ide.HerokuApp.com/editor#?sketch=5873a448c6a3ab040078c16d

**Comment by tjvr** [comment] 2017-01-09 15:33
@GoToLoop If you actually read the HTTP response, you'll see it says `<h1>Developer Inactive</h1>`. That's nothing to do with crossorigin; in fact you'll get the exact same response if you fetch your URL using `curl`!

In general, please try to check the problem is actually with crossorigin, before commenting on an unrelated issue.

**Comment by GoToLoop** [comment] 2017-01-09 15:40
Sorry, I'm still very noob regarding servers. But the link w/o http://CrossOrigin.me is currently active:
http://api.Zoopla.co.uk/api/v1/property_listings.xml?postcode=ip12&api_key=bmm77zppverakbnfnmtyuky3

**Comment by tjvr** [comment] 2017-01-09 15:53
@GoToLoop 
> in fact you'll get the exact same response if you fetch your URL using curl!

Whoops, I just checked again and this isn't true—I forgot to quote the URL.
It's possible it's doing something wrong regarding encoding; open a separate issue and @technoboy10 might have a look once he gets the chance. :)

**Comment by tjvr** [comment] 2017-01-09 15:57
@technoboy10 I suggest closing this issue as wontfix. Should definitely update the docs; open a new issue for that!

**Comment by GoToLoop** [comment] 2017-01-09 17:34
BtW, fixed the issue by changing to another CORS proxy:
http://CodePen.io/GoSubRoutine/pen/Qdjmrm/top/?editors=0012

**Comment by technoboy10** [comment] 2017-02-18 16:21
This is intentional. Need to write documentation though.

**Closed by technoboy10** 2017-02-18 16:21 UTC
Labels: wontfix
