### ISSUE TITLE
hstspreload.org multiple issues

### ISSUE THREAD

**Issue by galeksandrp** [technoboy10/crossorigin.me#74] opened 2016-12-20 03:12 UTC
* 403 Origin: header is required
* XMLHttpRequest cannot load https://crossorigin.me/https://hstspreload.org/api/v2/status?domain=hashicorp.com. The 'Access-Control-Allow-Origin' header contains multiple values '*, null', but only one is allowed. Origin 'https://fiddle.jshell.net' is therefore not allowed access.

Similar #73 #71

**Comment by tjvr** [comment] 2017-01-09 15:57
This issue is a duplicate. @technoboy10

**Comment by technoboy10** [comment] 2017-02-18 16:25
Duplicate of #73.

**Closed by technoboy10** 2017-02-18 16:25 UTC
